spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://app_db:3306/spend_track
    username: spend-track-admin
    password: admin-pass-123-!

  jpa:
    hibernate:
      ddl-auto: update

spend-track:
  bnc-transaction-prefix: "^(0[1-9]|1[0-2]) (0[1-9]|1[0-9]|2[0-9]|3[0-1]).*" # MM dd (date for BNC)
